# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Jasmer Sanjotra"
subtitle: "Algorithms | ML | Probability"
name: "Jasmer Singh Sanjotra"
description: "Personal portfolio showcasing my work in algorithms, probability theory, machine learning, and other projects."
url: "https://TheAlphaJas.github.io"
baseurl: ""
repository: "TheAlphaJas/username.github.io"
logo: "/assets/images/profile.jpg"
masthead_title: "Jasmer"

# Site Author
author:
  name: "Jasmer Singh Sanjotra"
  avatar: "/assets/images/profile.jpg"
  bio: "Researcher and developer focused on algorithms, probability theory, and machine learning."
  location: "IIT Indore, India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/username"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/username"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=your-id"
    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/username"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TheAlphaJas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jasmer-singh-sanjotra-a05b95250/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap" 
      url: "https://scholar.google.com/citations?user=NUCuUbIAAAAJ&hl=en"
    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/jasmer"

# Reading Files
include:
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache  # Essential for Minimal Mistakes
